cloud:
  aws:
    credentials:
      access-key: xxxxx    #Put Your Own access-key. Find/Generate it from (Click to your right side UserName navigation bar-> My Security Credentials -> IAM page -> access-key).
      secret-key: xxxxx    #Put Your Own secret-Key. Find/Generate it from (UserName -> My Security Credentials -> IAM page -> secret-key).
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: team-documents-dev


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 3MB
      max-file-size: 8MB
      max-request-size: 12MB

server:
  port: 8081
